Repository cloudflare/workerd, pull requests merged in 2025-08, with the labels that each got.

#4672 Additional argument type checking improvements in node:fs
  src/node/internal/internal_fs_callback.ts
  src/node/internal/internal_fs_streams.ts
  src/workerd/api/node/tests/fs-misc-test.js
  src/workerd/api/node/tests/fs-test.js
Labels: nodejs compat

#4564 [o11y] Return STW outcome properly
  src/workerd/io/trace-stream.c++
  src/workerd/io/worker-interface.capnp
Labels: o11y

#4594 Implements script for creating vendored package zip for tests
  src/pyodide/create_vendor_zip.py
  src/pyodide/make_snapshots.py
  src/pyodide/tool_utils.py
Labels: tooling

#4069 [build] Implement fast C23-based wd_cc_embed macro
  build/wd_cc_embed.bzl
  src/pyodide/BUILD.bazel
  src/pyodide/helpers.bzl
  src/pyodide/pyodide_extra.capnp
  src/workerd/io/BUILD.bazel
  src/workerd/io/compatibility-date-test.c++
  src/workerd/io/compatibility-date.c++
  src/workerd/io/compatibility-date.h
  src/workerd/io/supported-compatibility-date.capnp
  src/workerd/server/BUILD.bazel
  src/workerd/server/workerd-api.c++
  src/workerd/server/workerd.c++
Labels: tooling

#4774 Implement no-op emitDestroy method for AsyncResource
  src/workerd/api/node/async-hooks.h
Labels: nodejs compat

#4837 Python: Improvements to upload_bundles.py script
  src/pyodide/upload_bundles.py
Labels: python

#4894 [TD] Remove the obsolete jsg::Varargs type.
  src/workerd/jsg/jsg.h
  src/workerd/jsg/rtti-test.c++
  src/workerd/jsg/rtti.h
  src/workerd/jsg/type-wrapper.h
Labels: jsg

#4885 Python: Move the static methods defined on Response to FetchResponse
  src/pyodide/internal/_workers.py
Labels: python

#4848 Simplify tryResolveMainModule to use js.resolveModule
  src/workerd/io/worker.c++
  src/workerd/jsg/jsg.c++
  src/workerd/jsg/jsg.h
  src/workerd/jsg/resource.h
Labels: new module registry
